Update cli-test-npm.yml

diff --git a/.github/workflows/cli-test-npm.yml b/.github/workflows/cli-test-npm.yml
--- a/.github/workflows/cli-test-npm.yml
+++ b/.github/workflows/cli-test-npm.yml
@@ -27,17 +27,17 @@ jobs:
         uses: actions/checkout@v2
       -  name: Global - Testing installation of Twilio CLI (1)
          run: |
-          type twilio >/dev/null 2>&1 || twilio() { :; }
+          type twilio >/dev/null 2>&1 || { echo >&2 "I require twilio but it's not installed.  Aborting."; exit 1; }
           npm install -g twilio-cli@${{ github.event.inputs.version }}
           chmod +x ./.github/scripts/cmds-to-test.sh
           ./.github/scripts/cmds-to-test.sh
       
       - name: Global - Testing upgrade Twilio CLI (2)
         run: |
-         npm install -g twilio-cli@${{ github.event.inputs.version }}
-            npm install -g twilio-cli
-            chmod +x ./.github/scripts/cmds-to-test.sh
-            ./.github/scripts/cmds-to-test.sh
+          npm install -g twilio-cli@${{ github.event.inputs.version }}
+          npm install -g twilio-cli
+          chmod +x ./.github/scripts/cmds-to-test.sh
+          ./.github/scripts/cmds-to-test.sh
   
   test-local-installation:
     runs-on: ubuntu-latest
