Update cli-test-npm.yml

diff --git a/.github/workflows/cli-test-npm.yml b/.github/workflows/cli-test-npm.yml
--- a/.github/workflows/cli-test-npm.yml
+++ b/.github/workflows/cli-test-npm.yml
@@ -25,15 +25,13 @@ jobs:
          node-version: ${{ matrix.node-version }}
       - name: Check for cached twilio 
         run: | 
-         if ! command -v twilio > /dev/null; then twilio() { printf '%sNot installed, all good' "$*"; }; fi
+         if command -v twilio > /dev/null; then twilio() { printf '%sCLI is installed already, abort! ' "$*"; exit 1; }; fi
          twilio --version
       - name: Check Out Repo
         uses: actions/checkout@v2
       -  name: Global - Testing installation of Twilio CLI (1)
          run: |
           npm install -g twilio-cli@${{ github.event.inputs.version }}
-          if command -v twilio > /dev/null; then twilio() { printf '%sNot installed, all good' "$*"; exit 1; }; fi
-          twilio --version
           chmod +x ./.github/scripts/cmds-to-test.sh
           ./.github/scripts/cmds-to-test.sh
       
